name: continuous deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  release-charts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - name: run continuous deployment actions
        run: |
          ./earthly \
            --push \
            +continuous-deploy \
              --token ${{ secrets.GITHUB_TOKEN }}
