name: release new version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-binaries:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Extract short sha
        run: echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the binaries
        run: |
          ./earthly \
            --push \
            +release-binaries \
              --version=${{ env.RELEASE_VERSION }} \
              --commitSHA=${{ env.SHORT_SHA }} \
              --token ${{ secrets.GITHUB_TOKEN }}

  release-image:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Extract short sha
        run: echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set lower case owner name
        id: lower-case
        run: |
          echo "repository_owner=${OWNER,,}" >> ${GITHUB_OUTPUT}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Build and push the Docker image
        run: |
          ./earthly \
            --push \
            +build-image-multiarch \
              --version=${{ env.RELEASE_VERSION }} \
              --commitSHA=${{ env.SHORT_SHA }} \
              --image_name=ghcr.io/${{ steps.lower-case.outputs.repository_owner }}/prom-aggregation-gateway
